### ISSUE TITLE
Not pip-installable: package does not contain README.md

### ISSUE THREAD

**Issue by daniel-j-h** [DenisCarriere/gpsimage#1] opened 2014-08-15 14:32 UTC
Your package does not contain the files README.md or LICENSE.
But setup.py tries to read them. This of course fails:

```
(env)$ pip install gpsimage
Downloading/unpacking gpsimage
  Downloading gpsimage-0.0.1.tar.gz
  Running setup.py egg_info for package gpsimage
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/ex/env/build/gpsimage/setup.py", line 19, in <module>
        with open('README.md') as f:
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/tmp/ex/env/build/gpsimage/setup.py", line 19, in <module>
    with open('README.md') as f:
IOError: [Errno 2] No such file or directory: 'README.md'
```

Thanks,
Daniel

**Comment by DenisCarriere** [comment] 2014-08-18 21:13
Thank you Daniel for letting me know. I'll let you know when the problem is
fixed.

**Comment by DenisCarriere** [comment] 2014-08-18 23:48
Everything should be fixed now, I added the MANIFEST.in file and it works now.

**Closed as completed by DenisCarriere** 2014-08-18 23:48 UTC
